# Generated by Django 4.0.6 on 2022-07-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='organization',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
