# Generated by Django 4.0.6 on 2022-07-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fname',
        ),
    ]
