# Generated by Django 4.0.6 on 2022-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_fname_remove_teacher_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answer',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Unanswered', 'Unanswered')], default='Unanswered', max_length=10),
        ),
    ]
