# Generated by Django 4.0.6 on 2022-08-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doubt_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doubt')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
